<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::insert("INSERT INTO `countries` (`id`, `sortname`, `name`, `phone_code`, `created_at`, `updated_at`) VALUES
            (1, 'AF', 'Afghanistan', '+93', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (2, 'AL', 'Albania', '+355', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (3, 'DZ', 'Algeria', '+213', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (4, 'AS', 'American Samoa', '+1684', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (5, 'AD', 'Andorra', '+376', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (6, 'AO', 'Angola', '+244', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (7, 'AI', 'Anguilla', '+1264', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (8, 'AQ', 'Antarctica', '+0', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (9, 'AG', 'Antigua And Barbuda', '+1268', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (10, 'AR', 'Argentina', '+54', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (11, 'AM', 'Armenia', '+374', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (12, 'AW', 'Aruba', '+297', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (13, 'AU', 'Australia', '+61', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (14, 'AT', 'Austria', '+43', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (15, 'AZ', 'Azerbaijan', '+994', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (16, 'BS', 'Bahamas The', '+1242', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (17, 'BH', 'Bahrain', '+973', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (18, 'BD', 'Bangladesh', '+880', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (19, 'BB', 'Barbados', '+1246', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (20, 'BY', 'Belarus', '+375', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (21, 'BE', 'Belgium', '+32', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (22, 'BZ', 'Belize', '+501', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (23, 'BJ', 'Benin', '+229', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (24, 'BM', 'Bermuda', '+1441', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (25, 'BT', 'Bhutan', '+975', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (26, 'BO', 'Bolivia', '+591', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (27, 'BA', 'Bosnia and Herzegovina', '+387', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (28, 'BW', 'Botswana', '+267', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (29, 'BV', 'Bouvet Island', '+0', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (30, 'BR', 'Brazil', '+55', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (31, 'IO', 'British Indian Ocean Territory', '+246', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (32, 'BN', 'Brunei', '+673', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (33, 'BG', 'Bulgaria', '+359', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (34, 'BF', 'Burkina Faso', '+226', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (35, 'BI', 'Burundi', '+257', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (36, 'KH', 'Cambodia', '+855', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (37, 'CM', 'Cameroon', '+237', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (38, 'CA', 'Canada', '+1', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (39, 'CV', 'Cape Verde', '+238', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (40, 'KY', 'Cayman Islands', '+1345', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (41, 'CF', 'Central African Republic', '+236', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (42, 'TD', 'Chad', '+235', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (43, 'CL', 'Chile', '+56', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (44, 'CN', 'China', '+86', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (45, 'CX', 'Christmas Island', '+61', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (46, 'CC', 'Cocos (Keeling) Islands', '+672', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (47, 'CO', 'Colombia', '+57', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (48, 'KM', 'Comoros', '+269', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (49, 'CG', 'Republic Of The Congo', '+242', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (50, 'CD', 'Democratic Republic Of The Congo', '+242', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (51, 'CK', 'Cook Islands', '+682', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (52, 'CR', 'Costa Rica', '+506', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (53, 'CI', 'Cote D\'Ivoire (Ivory Coast)', '+225', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (54, 'HR', 'Croatia (Hrvatska)', '+385', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (55, 'CU', 'Cuba', '+53', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (56, 'CY', 'Cyprus', '+357', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (57, 'CZ', 'Czech Republic', '+420', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (58, 'DK', 'Denmark', '+45', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (59, 'DJ', 'Djibouti', '+253', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (60, 'DM', 'Dominica', '+1767', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (61, 'DO', 'Dominican Republic', '+1809', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (62, 'TP', 'East Timor', '+670', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (63, 'EC', 'Ecuador', '+593', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (64, 'EG', 'Egypt', '+20', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (65, 'SV', 'El Salvador', '+503', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (66, 'GQ', 'Equatorial Guinea', '+240', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (67, 'ER', 'Eritrea', '+291', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (68, 'EE', 'Estonia', '+372', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (69, 'ET', 'Ethiopia', '+251', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (70, 'XA', 'External Territories of Australia', '+61', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (71, 'FK', 'Falkland Islands', '+500', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (72, 'FO', 'Faroe Islands', '+298', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (73, 'FJ', 'Fiji Islands', '+679', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (74, 'FI', 'Finland', '+358', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (75, 'FR', 'France', '+33', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (76, 'GF', 'French Guiana', '+594', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (77, 'PF', 'French Polynesia', '+689', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (78, 'TF', 'French Southern Territories', '+0', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (79, 'GA', 'Gabon', '+241', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (80, 'GM', 'Gambia The', '+220', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (81, 'GE', 'Georgia', '+995', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (82, 'DE', 'Germany', '+49', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (83, 'GH', 'Ghana', '+233', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (84, 'GI', 'Gibraltar', '+350', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (85, 'GR', 'Greece', '+30', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (86, 'GL', 'Greenland', '+299', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (87, 'GD', 'Grenada', '+1473', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (88, 'GP', 'Guadeloupe', '+590', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (89, 'GU', 'Guam', '+1671', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (90, 'GT', 'Guatemala', '+502', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (91, 'XU', 'Guernsey and Alderney', '+44', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (92, 'GN', 'Guinea', '+224', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (93, 'GW', 'Guinea-Bissau', '+245', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (94, 'GY', 'Guyana', '+592', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (95, 'HT', 'Haiti', '+509', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (96, 'HM', 'Heard and McDonald Islands', '+0', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (97, 'HN', 'Honduras', '+504', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (98, 'HK', 'Hong Kong S.A.R.', '+852', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (99, 'HU', 'Hungary', '+36', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (100, 'IS', 'Iceland', '+354', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (101, 'IN', 'India', '+91', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (102, 'ID', 'Indonesia', '+62', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (103, 'IR', 'Iran', '+98', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (104, 'IQ', 'Iraq', '+964', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (105, 'IE', 'Ireland', '+353', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (106, 'IL', 'Israel', '+972', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (107, 'IT', 'Italy', '+39', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (108, 'JM', 'Jamaica', '+1876', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (109, 'JP', 'Japan', '+81', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (110, 'XJ', 'Jersey', '+44', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (111, 'JO', 'Jordan', '+962', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (112, 'KZ', 'Kazakhstan', '+7', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (113, 'KE', 'Kenya', '+254', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (114, 'KI', 'Kiribati', '+686', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (115, 'KP', 'Korea North', '+850', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (116, 'KR', 'Korea South', '+82', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (117, 'KW', 'Kuwait', '+965', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (118, 'KG', 'Kyrgyzstan', '+996', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (119, 'LA', 'Laos', '+856', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (120, 'LV', 'Latvia', '+371', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (121, 'LB', 'Lebanon', '+961', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (122, 'LS', 'Lesotho', '+266', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (123, 'LR', 'Liberia', '+231', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (124, 'LY', 'Libya', '+218', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (125, 'LI', 'Liechtenstein', '+423', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (126, 'LT', 'Lithuania', '+370', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (127, 'LU', 'Luxembourg', '+352', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (128, 'MO', 'Macau S.A.R.', '+853', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (129, 'MK', 'Macedonia', '+389', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (130, 'MG', 'Madagascar', '+261', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (131, 'MW', 'Malawi', '+265', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (132, 'MY', 'Malaysia', '+60', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (133, 'MV', 'Maldives', '+960', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (134, 'ML', 'Mali', '+223', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (135, 'MT', 'Malta', '+356', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (136, 'XM', 'Man (Isle of)', '+44', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (137, 'MH', 'Marshall Islands', '+692', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (138, 'MQ', 'Martinique', '+596', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (139, 'MR', 'Mauritania', '+222', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (140, 'MU', 'Mauritius', '+230', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (141, 'YT', 'Mayotte', '+269', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (142, 'MX', 'Mexico', '+52', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (143, 'FM', 'Micronesia', '+691', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (144, 'MD', 'Moldova', '+373', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (145, 'MC', 'Monaco', '+377', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (146, 'MN', 'Mongolia', '+976', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (147, 'MS', 'Montserrat', '+1664', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (148, 'MA', 'Morocco', '+212', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (149, 'MZ', 'Mozambique', '+258', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (150, 'MM', 'Myanmar', '+95', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (151, 'NA', 'Namibia', '+264', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (152, 'NR', 'Nauru', '+674', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (153, 'NP', 'Nepal', '+977', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (154, 'AN', 'Netherlands Antilles', '+599', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (155, 'NL', 'Netherlands The', '+31', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (156, 'NC', 'New Caledonia', '+687', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (157, 'NZ', 'New Zealand', '+64', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (158, 'NI', 'Nicaragua', '+505', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (159, 'NE', 'Niger', '+227', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (160, 'NG', 'Nigeria', '+234', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (161, 'NU', 'Niue', '+683', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (162, 'NF', 'Norfolk Island', '+672', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (163, 'MP', 'Northern Mariana Islands', '+1670', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (164, 'NO', 'Norway', '+47', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (165, 'OM', 'Oman', '+968', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (166, 'PK', 'Pakistan', '+92', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (167, 'PW', 'Palau', '+680', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (168, 'PS', 'Palestinian Territory Occupied', '+970', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (169, 'PA', 'Panama', '+507', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (170, 'PG', 'Papua new Guinea', '+675', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (171, 'PY', 'Paraguay', '+595', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (172, 'PE', 'Peru', '+51', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (173, 'PH', 'Philippines', '+63', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (174, 'PN', 'Pitcairn Island', '+0', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (175, 'PL', 'Poland', '+48', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (176, 'PT', 'Portugal', '+351', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (177, 'PR', 'Puerto Rico', '+1787', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (178, 'QA', 'Qatar', '+974', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (179, 'RE', 'Reunion', '+262', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (180, 'RO', 'Romania', '+40', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (181, 'RU', 'Russia', '+70', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (182, 'RW', 'Rwanda', '+250', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (183, 'SH', 'Saint Helena', '+290', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (184, 'KN', 'Saint Kitts And Nevis', '+1869', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (185, 'LC', 'Saint Lucia', '+1758', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (186, 'PM', 'Saint Pierre and Miquelon', '+508', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (187, 'VC', 'Saint Vincent And The Grenadines', '+1784', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (188, 'WS', 'Samoa', '+684', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (189, 'SM', 'San Marino', '+378', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (190, 'ST', 'Sao Tome and Principe', '+239', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (191, 'SA', 'Saudi Arabia', '+966', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (192, 'SN', 'Senegal', '+221', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (193, 'RS', 'Serbia', '+381', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (194, 'SC', 'Seychelles', '+248', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (195, 'SL', 'Sierra Leone', '+232', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (196, 'SG', 'Singapore', '+65', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (197, 'SK', 'Slovakia', '+421', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (198, 'SI', 'Slovenia', '+386', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (199, 'XG', 'Smaller Territories of the UK', '+44', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (200, 'SB', 'Solomon Islands', '+677', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (201, 'SO', 'Somalia', '+252', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (202, 'ZA', 'South Africa', '+27', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (203, 'GS', 'South Georgia', '+0', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (204, 'SS', 'South Sudan', '+211', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (205, 'ES', 'Spain', '+34', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (206, 'LK', 'Sri Lanka', '+94', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (207, 'SD', 'Sudan', '+249', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (208, 'SR', 'Suriname', '+597', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (209, 'SJ', 'Svalbard And Jan Mayen Islands', '+47', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (210, 'SZ', 'Swaziland', '+268', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (211, 'SE', 'Sweden', '+46', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (212, 'CH', 'Switzerland', '+41', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (213, 'SY', 'Syria', '+963', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (214, 'TW', 'Taiwan', '+886', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (215, 'TJ', 'Tajikistan', '+992', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (216, 'TZ', 'Tanzania', '+255', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (217, 'TH', 'Thailand', '+66', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (218, 'TG', 'Togo', '+228', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (219, 'TK', 'Tokelau', '+690', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (220, 'TO', 'Tonga', '+676', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (221, 'TT', 'Trinidad And Tobago', '+1868', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (222, 'TN', 'Tunisia', '+216', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (223, 'TR', 'Turkey', '+90', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (224, 'TM', 'Turkmenistan', '+7370', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (225, 'TC', 'Turks And Caicos Islands', '+1649', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (226, 'TV', 'Tuvalu', '+688', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (227, 'UG', 'Uganda', '+256', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (228, 'UA', 'Ukraine', '+380', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (229, 'AE', 'United Arab Emirates', '+971', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (230, 'GB', 'United Kingdom', '+44', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (231, 'US', 'United States', '+1', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (232, 'UM', 'United States Minor Outlying Islands', '+1', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (233, 'UY', 'Uruguay', '+598', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (234, 'UZ', 'Uzbekistan', '+998', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (235, 'VU', 'Vanuatu', '+678', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (236, 'VA', 'Vatican City State (Holy See)', '+39', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (237, 'VE', 'Venezuela', '+58', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (238, 'VN', 'Vietnam', '+84', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (239, 'VG', 'Virgin Islands (British)', '+1284', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (240, 'VI', 'Virgin Islands (US)', '+1340', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (241, 'WF', 'Wallis And Futuna Islands', '+681', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (242, 'EH', 'Western Sahara', '+212', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (243, 'YE', 'Yemen', '+967', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (244, 'YU', 'Yugoslavia', '+38', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (245, 'ZM', 'Zambia', '+260', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00')),
            (246, 'ZW', 'Zimbabwe', '+263', CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'), CONVERT_TZ(NOW(),@@session.time_zone,'+00:00'))
        ");
    }

}
